# Generated by Django 5.0.3 on 2024-03-18 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('user_email', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='userSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='userdef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('def_text', models.CharField(max_length=200)),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.term')),
                ('set_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.userset')),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='set_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.userset'),
        ),
    ]
