# Generated by Django 5.0.3 on 2024-03-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='term_id',
            new_name='term',
        ),
        migrations.AddField(
            model_name='term',
            name='termDef',
            field=models.CharField(default='temp definition//please replace', max_length=300),
        ),
        migrations.DeleteModel(
            name='userdef',
        ),
    ]
